### ISSUE TITLE
What is the licence for the files in this repository?

### ISSUE THREAD

**Issue by antoneliasson** [MentorEmbedded/meta-mentor#1021]
Best regards,
Anton Eliasson
Axis Communications AB

**Comment by kergoth** [comment]
Unless otherwise specified in the file headers, MIT. More explicitly, the OE/bitbake metadata is MIT, the patches are under the license of the project they apply to, and some of the scripts in scripts/ are GPLv2 at this time (as specified in their headers).


-Chris

________________________________

**Comment by antoneliasson** [comment]
Same as upstream then. Great! I'm specifically interested in bbpath-intercepts.bbclass. If it turns out useful to us we might make an effort to push it upstream eventually. Thanks for your quick response!

**Comment by kergoth** [comment]
Not a problem. Our intent was for that functionality to go upstream as well, we just haven't gotten around to it yet. If you want to pursue doing so, you're welcome to it! I appreciate the reminder on the license, we'll need to see about adding a LICENSE/COPYING file to the repository to avoid any future confusion in that regard. Thanks,


-Chris

________________________________
